sonar.projectKey=manutencao-conectada
sonar.projectName=Manutencao Conectada
sonar.projectVersion=1.0

sonar.projectBaseDir=../..

sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/migrations/**,**/coverage/**,**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

sonar.host.url=http://localhost:9000